### ISSUE TITLE
Using For Testing

### ISSUE THREAD

**Issue by JoshuaDoes** [umpox/zero-width-detection#2]
Hi,

I've just come across your article on Medium and found the link to this. I've never really messed around with NodeJS before, however I have used JavaScript in the past.

I'd like to know how to make your example demo here work, currently using an Apache2 web server on Ubuntu Server 17.04.

Sorry if this is a noobish question, and thanks in advance!

**Comment by umpox** [comment]
Hey no worries!

1. Clone the repository
2. Inside `/zero-width-detection` in your terminal run: `npm install`
3. Run `npm start`

You may need to [install Node.js & npm first](https://docs.npmjs.com/getting-started/installing-node#installing-npm-from-the-nodejs-site)
